#!/bin/bash
set -e

# Generate runtime environment configuration for frontend
# This file is loaded by the browser before the main application
API_URL_VALUE="${API_URL_EXTERNAL-/api}"
WS_URL_VALUE="${WS_URL_EXTERNAL-/api/ws}"
API_TIMEOUT_MS_VALUE="${API_TIMEOUT_MS-10000}"

cat > /var/www/html/env-config.js <<EOF
// Runtime environment configuration
// Generated by entrypoint.sh at container startup
window.ENV = {
  API_URL: "${API_URL_VALUE}",
  WS_URL: "${WS_URL_VALUE}",
  API_TIMEOUT_MS: "${API_TIMEOUT_MS_VALUE}"
};
EOF

echo "Generated env-config.js with:"
echo "  API_URL: ${API_URL_VALUE}"
echo "  WS_URL: ${WS_URL_VALUE}"
echo "  API_TIMEOUT_MS: ${API_TIMEOUT_MS_VALUE}"
echo "Runtime configuration:"
echo "  COORDINATOR_URL: ${COORDINATOR_URL:-<not set>}"
echo "  COORDINATOR_REALM: ${COORDINATOR_REALM:-realm1}"
echo "  UVICORN_WORKERS: ${UVICORN_WORKERS:-1}"
echo "  UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL:-info}"

if [ -z "${COORDINATOR_URL:-}" ]; then
  echo "WARNING: COORDINATOR_URL is not set. Backend will start in degraded mode."
fi

if [ ! -f "/app/commands.yaml" ]; then
  echo "WARNING: /app/commands.yaml is missing or not a regular file."
fi

if [ ! -f "/app/target_presets.json" ]; then
  echo "WARNING: /app/target_presets.json is missing or not a regular file."
fi

# Execute the command passed to the container (supervisord)
exec "$@"
