#!/bin/bash
set -e

# Generate runtime environment configuration for frontend
# This file is loaded by the browser before the main application
cat > /var/www/html/env-config.js <<EOF
// Runtime environment configuration
// Generated by entrypoint.sh at container startup
window.ENV = {
  API_URL: "/api",
  WS_URL: "${WS_URL_EXTERNAL:-/api/ws}"
};
EOF

echo "Generated env-config.js with:"
echo "  API_URL: /api"
echo "  WS_URL: ${WS_URL_EXTERNAL:-/api/ws}"

# Execute the command passed to the container (supervisord)
exec "$@"
