__EXPORTER_NAME__:
  NetworkSerialPort:
    host: "__SERIAL_HOST__"
    port: __SERIAL_PORT__
    speed: 115200
    protocol: "raw"
  NetworkService:
    address: "__SSH_ADDRESS__"
    username: "__SSH_USERNAME__"
    password: "__SSH_PASSWORD__"
